apps/app1/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
]

apps/app2/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<schmoo>\d+)$', views.index, name="index"),
    url(r'^post_test$', views.post_test, name="post_test"),
]

named_routes_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^app1/', include('apps.app1.urls', namespace='app1')),
    url(r'^app2/', include('apps.app2.urls', namespace='app2' )),
    url(r'^admin/', admin.site.urls),
]

apps/app1/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/app2/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/app1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        'ids': [1,2,3,4]
    }
    return render(request, 'app1/index.html', context)

apps/app2/views.py
from django.shortcuts import render, redirect, reverse

# Create your views here.
def index(request, schmoo):
    print id
    return render(request, 'app2/index.html')

def post_test(request):
    print "here"
    return redirect(reverse('app1:index'))

apps/app1/templates/app1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <h1>App 1</h1>
    {% for id in ids%}
      <a href="{% url 'app2:index' schmoo=id %}">Go to App 2</a>
    {% endfor %}
</body>
</html>

apps/app2/templates/app2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <h1>App 2</h1>
  <a href="{% url 'app1:index' %}">Go to App 1</a>

  <form action="{% url 'app2:post_test'%}" method="Post">
    {% csrf_token %}
    <input type="hidden" value="100" name="hidden">
    <input type="submit" value="Go!">
  </form>
</body>
</html>